# Generated by Django 6.1 on 2026-08-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_service_accounts_apikeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
            ],
            options={
                'verbose_name': 'service account',
                'verbose_name_plural': 'service accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
    ]
