# Generated by Django 6.1 on 2026-08-15 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_hero_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventobservation',
            name='consecutive_misses',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive runs this event was expected but not seen.'),
        ),
        migrations.AddField(
            model_name='eventobservation',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stable per-event identity for run-over-run matching.', max_length=255),
        ),
        migrations.AddField(
            model_name='eventobservation',
            name='last_observed_run',
            field=models.ForeignKey(blank=True, help_text='Most recent succeeded run that observed this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_observations', to='events.ingestionrun'),
        ),
        migrations.AddField(
            model_name='eventobservation',
            name='lifecycle',
            field=models.CharField(choices=[('new', 'New'), ('observed', 'Observed'), ('updated', 'Updated'), ('postponed', 'Postponed'), ('no_longer_observed', 'No longer observed'), ('completed', 'Completed')], db_index=True, default='new', help_text='Run-over-run classification (orthogonal to review status).', max_length=25),
        ),
        migrations.AddField(
            model_name='eventobservation',
            name='lifecycle_note',
            field=models.TextField(blank=True, default='', help_text='Provenance for an auto-applied lifecycle change.'),
        ),
        migrations.AddField(
            model_name='eventobservation',
            name='lifecycle_set_at',
            field=models.DateTimeField(blank=True, help_text='When lifecycle was last set to a terminal state.', null=True),
        ),
        migrations.AddField(
            model_name='eventobservation',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='Newer observation that replaced this one (if matched/updated).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='events.eventobservation'),
        ),
        migrations.AddIndex(
            model_name='eventobservation',
            index=models.Index(fields=['source', 'lifecycle'], name='events_obs_src_life_idx'),
        ),
        migrations.AddIndex(
            model_name='eventobservation',
            index=models.Index(fields=['source', 'event_key', 'lifecycle'], name='events_obs_key_life_idx'),
        ),
        migrations.AddIndex(
            model_name='eventobservation',
            index=models.Index(fields=['source', 'last_observed_run'], name='events_obs_last_run_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventobservation',
            constraint=models.UniqueConstraint(condition=models.Q(('event_key__gt', ''), ('run__isnull', False)), fields=('source', 'event_key', 'run'), name='unique_obs_per_run_per_key'),
        ),
    ]
