# Generated by Django 6.1 on 2026-08-08 12:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.PositiveBigIntegerField(blank=True, db_index=True, help_text='Stable GeoNames id; idempotency key for re-seeding.', null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('default_radius_km', models.PositiveIntegerField(default=15, help_text='Suggested search radius (km) for ?near_city=.')),
                ('population', models.PositiveBigIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
    ]
