import pytest
from django.contrib.auth.models import Group
from django.utils import timezone

from locations.models import City

from .models import Category, Event, EventSource, Organization, Venue


def test_event_str_includes_start_date(db, api_client):
    venue = Venue.objects.create(name="Town Hall", city="Berlin")
    event = Event.objects.create(
        title="PyNight",
        starts_at=timezone.now(),
        venue=venue,
    )
    assert "PyNight" in str(event)


def test_category_slug_is_autogenerated(db, api_client):
    category = Category.objects.create(name="Tech Meetup")
    assert category.slug == "tech-meetup"


def test_event_list_endpoint_returns_serialized_fields(db, api_client):
    venue = Venue.objects.create(name="Town Hall", city="Berlin")
    cat = Category.objects.create(name="Tech")
    Event.objects.create(title="PyNight", starts_at=timezone.now(), venue=venue)
    response = api_client.get("/api/events/", format="json")
    assert response.status_code == 200
    results = response.data["results"] if "results" in response.data else response.data
    assert len(results) == 1
    item = results[0]
    assert item["title"] == "PyNight"
    assert item["venue"]["city"] == "Berlin"
    # Location fields are present (null when none set).
    assert item["latitude"] is None
    assert item["longitude"] is None


def test_event_filter_by_category(db, api_client):
    venue = Venue.objects.create(name="Hall", city="Berlin")
    music = Category.objects.create(name="Music")
    tech = Category.objects.create(name="Tech")
    Event.objects.create(title="Concert", starts_at=timezone.now(), venue=venue)
    Event.objects.create(title="PyNight", starts_at=timezone.now(), venue=venue)
    Event.objects.get(title="Concert").categories.add(music)
    Event.objects.get(title="PyNight").categories.add(tech)

    response = api_client.get(f"/api/events/?category={tech.id}", format="json")
    assert response.status_code == 200
    results = response.data["results"] if "results" in response.data else response.data
    titles = {item["title"] for item in results}
    assert titles == {"PyNight"}


def test_event_search(db, api_client):
    venue = Venue.objects.create(name="Hall", city="Berlin")
    Event.objects.create(title="Django Meetup", starts_at=timezone.now(), venue=venue)
    Event.objects.create(
        title="Board Game Night",
        description="Fun and games",
        starts_at=timezone.now(),
        venue=venue,
    )
    response = api_client.get("/api/events/?search=django", format="json")
    assert response.status_code == 200
    results = response.data["results"] if "results" in response.data else response.data
    assert {item["title"] for item in results} == {"Django Meetup"}


def test_create_event_sets_created_by(db, authed_client):
    venue = Venue.objects.create(name="Hall", city="Berlin")
    payload = {
        "title": "Created Event",
        "starts_at": timezone.now().isoformat(),
        "venue_id": venue.id,
    }
    response = authed_client.post("/api/events/", payload, format="json")
    assert response.status_code == 201
    assert Event.objects.get(title="Created Event").created_by.username == "alice"


# --- Geospatial proximity ----------------------------------------------------


def test_create_event_with_lat_lon_stores_location(db, authed_client):
    payload = {
        "title": "Berlin Meetup",
        "starts_at": timezone.now().isoformat(),
        "latitude": 52.52,
        "longitude": 13.405,
    }
    response = authed_client.post("/api/events/", payload, format="json")
    assert response.status_code == 201
    event = Event.objects.get(title="Berlin Meetup")
    assert event.location is not None
    assert round(event.location.y, 3) == 52.52  # latitude
    assert round(event.location.x, 3) == 13.405  # longitude
    # Echoed in the response.
    assert response.data["latitude"] == 52.52


def test_proximity_returns_nearby_events_only(db, api_client):
    # Berlin centre ~52.52, 13.405 ; Potsdam ~52.39, 13.06 (≈30 km away).
    Event.objects.create(
        title="Berlin PyNight",
        starts_at=timezone.now(),
        location="POINT(13.405 52.52)",
    )
    Event.objects.create(
        title="Potsdam Meetup",
        starts_at=timezone.now(),
        location="POINT(13.06 52.39)",
    )
    response = api_client.get(
        "/api/events/?lat=52.52&lon=13.405&radius_km=10", format="json"
    )
    assert response.status_code == 200
    results = response.data["results"] if "results" in response.data else response.data
    titles = {item["title"] for item in results}
    assert titles == {"Berlin PyNight"}


def test_proximity_annotates_distance_and_orders_nearest(db, api_client):
    Event.objects.create(
        title="Near",
        starts_at=timezone.now(),
        location="POINT(13.41 52.52)",
    )
    Event.objects.create(
        title="Far",
        starts_at=timezone.now(),
        location="POINT(13.50 52.55)",
    )
    response = api_client.get(
        "/api/events/?lat=52.52&lon=13.405&radius_km=100", format="json"
    )
    assert response.status_code == 200
    results = response.data["results"] if "results" in response.data else response.data
    assert [item["title"] for item in results] == ["Near", "Far"]
    assert results[0]["distance"] < results[1]["distance"]
    assert results[0]["distance"] is not None


def test_proximity_requires_all_three_params(db, api_client):
    response = api_client.get("/api/events/?lat=52.52", format="json")
    assert response.status_code == 400


# --- Ownership ----------------------------------------------------------------


def test_owner_can_update_and_delete_own_event(db, authed_client, user):
    event = Event.objects.create(title="Mine", starts_at=timezone.now(), created_by=user)
    response = authed_client.patch(
        f"/api/events/{event.id}/", {"title": "Updated"}, format="json"
    )
    assert response.status_code == 200
    assert response.data["title"] == "Updated"
    response = authed_client.delete(f"/api/events/{event.id}/")
    assert response.status_code == 204


def test_other_user_cannot_update_someone_elses_event(db, authed_client, other_user):
    event = Event.objects.create(
        title="Theirs", starts_at=timezone.now(), created_by=other_user
    )
    response = authed_client.patch(
        f"/api/events/{event.id}/", {"title": "Hacked"}, format="json"
    )
    assert response.status_code == 403


def test_owner_group_member_can_update(db, api_client, user, other_user, editors_group):
    event = Event.objects.create(
        title="Group Owned", starts_at=timezone.now(), created_by=user,
        owner_group=editors_group,
    )
    other_user.groups.add(editors_group)
    api_client.force_authenticate(user=other_user)
    response = api_client.patch(
        f"/api/events/{event.id}/", {"title": "Edited by group member"}, format="json"
    )
    assert response.status_code == 200


def test_service_account_needs_add_perm_to_create(db, api_client, user, editors_group):
    from django.contrib.auth import get_user_model
    from django.contrib.auth.models import Permission

    User = get_user_model()

    user.is_service_account = True
    user.save()
    api_client.force_authenticate(user=user)

    payload = {"title": "SA Event", "starts_at": timezone.now().isoformat()}
    # No add_event permission yet → 403.
    assert api_client.post("/api/events/", payload, format="json").status_code == 403

    # Grant add_event via the group → 201.
    perm = Permission.objects.get(codename="add_event", content_type__app_label="events")
    editors_group.permissions.add(perm)
    user.groups.add(editors_group)
    # Refetch the user: the first request cached the negative has_perm() result
    # on the in-memory instance. A fresh fetch (as the auth backend would give
    # on a real second request) picks up the newly granted group permission.
    user = User.objects.get(pk=user.pk)
    api_client.force_authenticate(user=user)
    assert api_client.post("/api/events/", payload, format="json").status_code == 201


# --- Proximity by city (?near_city=) -----------------------------------------


def _berlin_city():
    return City.objects.create(
        geoname_id=2950159, name="Berlin", country="Germany", country_code="DE",
        location="POINT(13.405 52.52)", population=3_400_000,
        default_radius_km=45, timezone="Europe/Berlin", slug="berlin-de",
    )


def test_near_city_returns_nearby_events_with_distance(db, api_client):
    _berlin_city()
    Event.objects.create(title="Berlin PyNight", starts_at=timezone.now(),
                         location="POINT(13.41 52.52)")
    Event.objects.create(title="Potsdam Meetup", starts_at=timezone.now(),
                         location="POINT(13.06 52.39)")  # ~27 km from Berlin
    response = api_client.get("/api/events/?near_city=berlin-de", format="json")
    assert response.status_code == 200
    results = response.data["results"] if "results" in response.data else response.data
    # Both within the default 45 km radius; nearest first, distance annotated.
    assert [r["title"] for r in results] == ["Berlin PyNight", "Potsdam Meetup"]
    assert results[0]["distance"] < results[1]["distance"]
    assert results[0]["distance"] is not None


def test_near_city_radius_override_excludes_far(db, api_client):
    _berlin_city()
    Event.objects.create(title="Berlin PyNight", starts_at=timezone.now(),
                         location="POINT(13.41 52.52)")
    Event.objects.create(title="Potsdam Meetup", starts_at=timezone.now(),
                         location="POINT(13.06 52.39)")
    response = api_client.get(
        "/api/events/?near_city=berlin-de&radius_km=10", format="json"
    )
    assert response.status_code == 200
    results = response.data["results"] if "results" in response.data else response.data
    assert {r["title"] for r in results} == {"Berlin PyNight"}


def test_near_city_unknown_slug_returns_400(db, api_client):
    response = api_client.get("/api/events/?near_city=nope-xx", format="json")
    assert response.status_code == 400


def test_near_city_with_lat_is_rejected(db, api_client):
    response = api_client.get(
        "/api/events/?near_city=berlin-de&lat=52.52", format="json"
    )
    assert response.status_code == 400


# --- Model defaults / provenance -------------------------------------------


def test_event_defaults_published_physical_other(db, api_client):
    """New events default to published/physical/other with null provenance so
    the existing hand-curated catalog stays public and every pre-existing test
    that creates an Event with no new fields keeps passing."""
    event = Event.objects.create(title="Defaults", starts_at=timezone.now())
    assert event.status == Event.Status.PUBLISHED
    assert event.event_type == Event.EventType.OTHER
    assert event.attendance_mode == Event.AttendanceMode.PHYSICAL
    assert event.original_url == ""
    assert event.original_platform == ""
    assert event.source_id is None
    assert event.promoted_from_id is None


def test_organization_slug_is_autogenerated(db):
    org = Organization.objects.create(name="Berlin Tech Meetups")
    assert org.slug == "berlin-tech-meetups"


# --- Hero image ---------------------------------------------------------------


def _png_bytes():
    """A tiny valid PNG (built with Pillow, the ImageField dependency)."""
    from io import BytesIO

    from PIL import Image

    buf = BytesIO()
    Image.new("RGB", (10, 10), (255, 0, 0)).save(buf, format="PNG")
    return buf.getvalue()


def test_event_with_hero_image_serializes_to_url(db, api_client, settings, tmp_path):
    from django.core.files.uploadedfile import SimpleUploadedFile

    # Keep test media out of the real MEDIA_ROOT.
    settings.MEDIA_ROOT = str(tmp_path)
    event = Event.objects.create(title="Hero Event", starts_at=timezone.now())
    event.hero_image.save(
        "hero.png",
        SimpleUploadedFile("hero.png", _png_bytes(), content_type="image/png"),
        save=False,
    )
    event.save(update_fields=["hero_image"])

    response = api_client.get(f"/api/events/{event.id}/", format="json")
    assert response.status_code == 200
    # Read-only absolute URL is exposed (uploads happen in the backoffice).
    assert response.data["hero_image"] is not None
    assert response.data["hero_image"].endswith("hero.png")


def test_event_without_hero_image_serializes_null(db, api_client):
    event = Event.objects.create(title="No Hero", starts_at=timezone.now())
    response = api_client.get(f"/api/events/{event.id}/", format="json")
    assert response.status_code == 200
    assert response.data["hero_image"] is None


def test_event_source_unique_per_organization(db, organization):
    from django.db import IntegrityError, transaction

    EventSource.objects.create(organization=organization, url="https://x")
    # Isolate the constraint violation in its own atomic block so the broken
    # inner transaction is rolled back without poisoning the test's outer one.
    with pytest.raises(IntegrityError):
        with transaction.atomic():
            EventSource.objects.create(organization=organization, url="https://x")
    # A different org may reuse the same URL.
    other = Organization.objects.create(name="Other Org")
    EventSource.objects.create(organization=other, url="https://x")


def test_event_source_due_returns_only_approved_active_due(db, organization):
    from datetime import timedelta

    approved_due = EventSource.objects.create(
        organization=organization, url="https://1", is_approved=True
    )  # never fetched → due
    approved_soon = EventSource.objects.create(
        organization=organization, url="https://2", is_approved=True,
        next_due_at=timezone.now() + timedelta(hours=1),
    )  # not due yet
    approved_overdue = EventSource.objects.create(
        organization=organization, url="https://3", is_approved=True,
        next_due_at=timezone.now() - timedelta(hours=1),
    )  # due
    unapproved = EventSource.objects.create(
        organization=organization, url="https://4", is_approved=False
    )  # not approved
    paused = EventSource.objects.create(
        organization=organization, url="https://5", is_approved=True, is_active=False
    )  # paused

    due = set(EventSource.due().values_list("id", flat=True))
    assert due == {approved_due.id, approved_overdue.id}
    assert approved_soon.id not in due
    assert unapproved.id not in due
    assert paused.id not in due


# --- Public visibility & lifecycle ------------------------------------------


def test_public_list_shows_only_published(db, api_client):
    Event.objects.create(title="Pub", starts_at=timezone.now())
    Event.objects.create(
        title="Draft", starts_at=timezone.now(), status=Event.Status.DRAFT
    )
    Event.objects.create(
        title="Archived", starts_at=timezone.now(), status=Event.Status.ARCHIVED
    )
    response = api_client.get("/api/events/", format="json")
    results = response.data["results"] if "results" in response.data else response.data
    assert {i["title"] for i in results} == {"Pub"}


def test_operator_sees_all_statuses(db, authed_client, user):
    # Grant the change perm so alice is an operator.
    from django.contrib.auth.models import Permission

    user.user_permissions.add(
        Permission.objects.get(content_type__app_label="events", codename="change_event")
    )
    from django.contrib.auth import get_user_model

    user = get_user_model().objects.get(pk=user.pk)  # refetch (perm cache gotcha)
    authed_client.force_authenticate(user=user)

    Event.objects.create(title="Pub", starts_at=timezone.now())
    Event.objects.create(
        title="Draft", starts_at=timezone.now(), status=Event.Status.DRAFT
    )
    response = authed_client.get("/api/events/", format="json")
    results = response.data["results"] if "results" in response.data else response.data
    assert {i["title"] for i in results} == {"Pub", "Draft"}


def test_owner_can_retrieve_own_draft(db, authed_client, user, api_client):
    event = Event.objects.create(
        title="My Draft", starts_at=timezone.now(),
        created_by=user, status=Event.Status.DRAFT,
    )
    # Anon can't see it.
    assert api_client.get(f"/api/events/{event.id}/").status_code == 404
    # Owner can.
    assert authed_client.get(f"/api/events/{event.id}/").status_code == 200


def test_lifecycle_publish_action_sets_published_at(db, authed_client, user):
    from django.contrib.auth.models import Permission

    user.user_permissions.add(
        Permission.objects.get(content_type__app_label="events", codename="change_event")
    )
    from django.contrib.auth import get_user_model

    user = get_user_model().objects.get(pk=user.pk)
    authed_client.force_authenticate(user=user)

    event = Event.objects.create(
        title="Draft", starts_at=timezone.now(),
        created_by=user, status=Event.Status.DRAFT,
    )
    response = authed_client.post(f"/api/events/{event.id}/publish/")
    assert response.status_code == 200
    event.refresh_from_db()
    assert event.status == Event.Status.PUBLISHED
    assert event.published_at is not None

    # Cancel → archived lifecycle also reachable.
    cancel = authed_client.post(f"/api/events/{event.id}/cancel/")
    assert cancel.status_code == 200
    event.refresh_from_db()
    assert event.status == Event.Status.CANCELLED
    assert event.cancelled_at is not None


def test_lifecycle_action_requires_change_perm(db, authed_client, user):
    event = Event.objects.create(title="Theirs", starts_at=timezone.now())
    # alice owns nothing here and lacks change_event → 403.
    response = authed_client.post(f"/api/events/{event.id}/publish/")
    assert response.status_code == 403


# --- Filters ----------------------------------------------------------------


def test_filter_by_organization_id(db, api_client, organization):
    other = Organization.objects.create(name="Other")
    Event.objects.create(
        title="OrgA", starts_at=timezone.now(), organization=organization
    )
    Event.objects.create(title="OrgB", starts_at=timezone.now(), organization=other)
    response = api_client.get(f"/api/events/?organization={organization.id}", format="json")
    results = response.data["results"] if "results" in response.data else response.data
    assert {i["title"] for i in results} == {"OrgA"}


def test_filter_by_organization_slug(db, api_client, organization):
    Event.objects.create(
        title="OrgA", starts_at=timezone.now(), organization=organization
    )
    response = api_client.get(
        f"/api/events/?organization_slug={organization.slug}", format="json"
    )
    results = response.data["results"] if "results" in response.data else response.data
    assert {i["title"] for i in results} == {"OrgA"}


def test_filter_by_event_type_and_attendance_mode(db, api_client):
    Event.objects.create(
        title="Meetup", starts_at=timezone.now(),
        event_type=Event.EventType.MEETUP,
    )
    Event.objects.create(
        title="Conf", starts_at=timezone.now(),
        event_type=Event.EventType.CONFERENCE,
    )
    Event.objects.create(
        title="Online", starts_at=timezone.now(),
        attendance_mode=Event.AttendanceMode.ONLINE,
    )
    r = api_client.get("/api/events/?event_type=meetup", format="json")
    results = r.data["results"] if "results" in r.data else r.data
    assert {i["title"] for i in results} == {"Meetup"}

    r = api_client.get("/api/events/?attendance_mode=online", format="json")
    results = r.data["results"] if "results" in r.data else r.data
    assert {i["title"] for i in results} == {"Online"}


# --- Proximity excludes online ---------------------------------------------


def test_proximity_excludes_online_events(db, api_client):
    # An online event carrying a location right at the query point must NOT be
    # returned by proximity (it has no physical presence). Hybrid stays in.
    Event.objects.create(
        title="Online Here", starts_at=timezone.now(),
        location="POINT(13.405 52.52)", attendance_mode=Event.AttendanceMode.ONLINE,
    )
    Event.objects.create(
        title="Hybrid Here", starts_at=timezone.now(),
        location="POINT(13.405 52.52)", attendance_mode=Event.AttendanceMode.HYBRID,
    )
    response = api_client.get(
        "/api/events/?lat=52.52&lon=13.405&radius_km=10", format="json"
    )
    results = response.data["results"] if "results" in response.data else response.data
    assert {i["title"] for i in results} == {"Hybrid Here"}


# --- Public organizations API ----------------------------------------------


def test_public_organizations_excludes_inactive(db, api_client):
    Organization.objects.create(name="Active Org")
    Organization.objects.create(name="Gone Org", is_active=False)
    response = api_client.get("/api/organizations/", format="json")
    results = response.data["results"] if "results" in response.data else response.data
    names = {i["name"] for i in results}
    assert "Active Org" in names
    assert "Gone Org" not in names
    # Public payload is narrow (no owner/is_active internals).
    assert set(results[0].keys()) == {"id", "name", "slug", "description", "website"}


def test_organization_detail_by_slug(db, api_client, organization):
    response = api_client.get(
        f"/api/organizations/{organization.slug}/", format="json"
    )
    assert response.status_code == 200
    assert response.data["name"] == organization.name


def test_organization_events_action_returns_published_only(db, api_client, organization):
    Event.objects.create(
        title="Pub", starts_at=timezone.now(), organization=organization
    )
    Event.objects.create(
        title="Draft", starts_at=timezone.now(),
        organization=organization, status=Event.Status.DRAFT,
    )
    response = api_client.get(
        f"/api/organizations/{organization.slug}/events/", format="json"
    )
    assert response.status_code == 200
    results = response.data["results"] if "results" in response.data else response.data
    assert {i["title"] for i in results} == {"Pub"}