from django.contrib.auth.models import Group
from django.utils import timezone

from .models import Category, Event, Venue


def test_event_str_includes_start_date(db, api_client):
    venue = Venue.objects.create(name="Town Hall", city="Berlin")
    event = Event.objects.create(
        title="PyNight",
        starts_at=timezone.now(),
        venue=venue,
    )
    assert "PyNight" in str(event)


def test_category_slug_is_autogenerated(db, api_client):
    category = Category.objects.create(name="Tech Meetup")
    assert category.slug == "tech-meetup"


def test_event_list_endpoint_returns_serialized_fields(db, api_client):
    venue = Venue.objects.create(name="Town Hall", city="Berlin")
    cat = Category.objects.create(name="Tech")
    Event.objects.create(title="PyNight", starts_at=timezone.now(), venue=venue)
    response = api_client.get("/api/events/", format="json")
    assert response.status_code == 200
    results = response.data["results"] if "results" in response.data else response.data
    assert len(results) == 1
    item = results[0]
    assert item["title"] == "PyNight"
    assert item["venue"]["city"] == "Berlin"
    # Location fields are present (null when none set).
    assert item["latitude"] is None
    assert item["longitude"] is None


def test_event_filter_by_category(db, api_client):
    venue = Venue.objects.create(name="Hall", city="Berlin")
    music = Category.objects.create(name="Music")
    tech = Category.objects.create(name="Tech")
    Event.objects.create(title="Concert", starts_at=timezone.now(), venue=venue)
    Event.objects.create(title="PyNight", starts_at=timezone.now(), venue=venue)
    Event.objects.get(title="Concert").categories.add(music)
    Event.objects.get(title="PyNight").categories.add(tech)

    response = api_client.get(f"/api/events/?category={tech.id}", format="json")
    assert response.status_code == 200
    results = response.data["results"] if "results" in response.data else response.data
    titles = {item["title"] for item in results}
    assert titles == {"PyNight"}


def test_event_search(db, api_client):
    venue = Venue.objects.create(name="Hall", city="Berlin")
    Event.objects.create(title="Django Meetup", starts_at=timezone.now(), venue=venue)
    Event.objects.create(
        title="Board Game Night",
        description="Fun and games",
        starts_at=timezone.now(),
        venue=venue,
    )
    response = api_client.get("/api/events/?search=django", format="json")
    assert response.status_code == 200
    results = response.data["results"] if "results" in response.data else response.data
    assert {item["title"] for item in results} == {"Django Meetup"}


def test_create_event_sets_created_by(db, authed_client):
    venue = Venue.objects.create(name="Hall", city="Berlin")
    payload = {
        "title": "Created Event",
        "starts_at": timezone.now().isoformat(),
        "venue_id": venue.id,
    }
    response = authed_client.post("/api/events/", payload, format="json")
    assert response.status_code == 201
    assert Event.objects.get(title="Created Event").created_by.username == "alice"


# --- Geospatial proximity ----------------------------------------------------


def test_create_event_with_lat_lon_stores_location(db, authed_client):
    payload = {
        "title": "Berlin Meetup",
        "starts_at": timezone.now().isoformat(),
        "latitude": 52.52,
        "longitude": 13.405,
    }
    response = authed_client.post("/api/events/", payload, format="json")
    assert response.status_code == 201
    event = Event.objects.get(title="Berlin Meetup")
    assert event.location is not None
    assert round(event.location.y, 3) == 52.52  # latitude
    assert round(event.location.x, 3) == 13.405  # longitude
    # Echoed in the response.
    assert response.data["latitude"] == 52.52


def test_proximity_returns_nearby_events_only(db, api_client):
    # Berlin centre ~52.52, 13.405 ; Potsdam ~52.39, 13.06 (≈30 km away).
    Event.objects.create(
        title="Berlin PyNight",
        starts_at=timezone.now(),
        location="POINT(13.405 52.52)",
    )
    Event.objects.create(
        title="Potsdam Meetup",
        starts_at=timezone.now(),
        location="POINT(13.06 52.39)",
    )
    response = api_client.get(
        "/api/events/?lat=52.52&lon=13.405&radius_km=10", format="json"
    )
    assert response.status_code == 200
    results = response.data["results"] if "results" in response.data else response.data
    titles = {item["title"] for item in results}
    assert titles == {"Berlin PyNight"}


def test_proximity_annotates_distance_and_orders_nearest(db, api_client):
    Event.objects.create(
        title="Near",
        starts_at=timezone.now(),
        location="POINT(13.41 52.52)",
    )
    Event.objects.create(
        title="Far",
        starts_at=timezone.now(),
        location="POINT(13.50 52.55)",
    )
    response = api_client.get(
        "/api/events/?lat=52.52&lon=13.405&radius_km=100", format="json"
    )
    assert response.status_code == 200
    results = response.data["results"] if "results" in response.data else response.data
    assert [item["title"] for item in results] == ["Near", "Far"]
    assert results[0]["distance"] < results[1]["distance"]
    assert results[0]["distance"] is not None


def test_proximity_requires_all_three_params(db, api_client):
    response = api_client.get("/api/events/?lat=52.52", format="json")
    assert response.status_code == 400


# --- Ownership ----------------------------------------------------------------


def test_owner_can_update_and_delete_own_event(db, authed_client, user):
    event = Event.objects.create(title="Mine", starts_at=timezone.now(), created_by=user)
    response = authed_client.patch(
        f"/api/events/{event.id}/", {"title": "Updated"}, format="json"
    )
    assert response.status_code == 200
    assert response.data["title"] == "Updated"
    response = authed_client.delete(f"/api/events/{event.id}/")
    assert response.status_code == 204


def test_other_user_cannot_update_someone_elses_event(db, authed_client, other_user):
    event = Event.objects.create(
        title="Theirs", starts_at=timezone.now(), created_by=other_user
    )
    response = authed_client.patch(
        f"/api/events/{event.id}/", {"title": "Hacked"}, format="json"
    )
    assert response.status_code == 403


def test_owner_group_member_can_update(db, api_client, user, other_user, editors_group):
    event = Event.objects.create(
        title="Group Owned", starts_at=timezone.now(), created_by=user,
        owner_group=editors_group,
    )
    other_user.groups.add(editors_group)
    api_client.force_authenticate(user=other_user)
    response = api_client.patch(
        f"/api/events/{event.id}/", {"title": "Edited by group member"}, format="json"
    )
    assert response.status_code == 200


def test_service_account_needs_add_perm_to_create(db, api_client, user, editors_group):
    from django.contrib.auth import get_user_model
    from django.contrib.auth.models import Permission

    User = get_user_model()

    user.is_service_account = True
    user.save()
    api_client.force_authenticate(user=user)

    payload = {"title": "SA Event", "starts_at": timezone.now().isoformat()}
    # No add_event permission yet → 403.
    assert api_client.post("/api/events/", payload, format="json").status_code == 403

    # Grant add_event via the group → 201.
    perm = Permission.objects.get(codename="add_event", content_type__app_label="events")
    editors_group.permissions.add(perm)
    user.groups.add(editors_group)
    # Refetch the user: the first request cached the negative has_perm() result
    # on the in-memory instance. A fresh fetch (as the auth backend would give
    # on a real second request) picks up the newly granted group permission.
    user = User.objects.get(pk=user.pk)
    api_client.force_authenticate(user=user)
    assert api_client.post("/api/events/", payload, format="json").status_code == 201